base_url = "https://beta.yannicka.fr/"
title = "Yannicka"
description = "Le blog d'un d√©veloppeur"
default_language = "fr"
generate_feeds = true
author = "Yannick A."

taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
